class kalimdor::osd::base {
  $osd_options = {
    # osd client
    osd_client_message_cap            => 1000,
    osd_client_message_size_cap       => 524288000,
    osd_client_op_priority            => 63,
    ms_dispatch_throttle_bytes        => 104857600,

    # osd op
    osd_pg_object_context_cache_count   => 64,
    osd_op_threads                      => 2,
    osd_op_pq_max_tokens_per_priority   => 4194304,
    osd_op_pq_min_cost                  => 65536,
    osd_op_num_threads_per_shard        => 2,       # related to the number of cpu cores
    osd_op_num_shards                   => 5,       # related to pg numbers
    osd_op_thread_timeout               => 15,
    osd_op_thread_suicide_timeout       => 150,
    osd_op_complaint_time               => 20,      # related to heartbeat interval
    osd_op_log_threshold                => 5,
    osd_op_history_size                 => 20,
    osd_op_history_duration             => 600,
    osd_min_pg_log_entries              => 3000,
    osd_max_pg_log_entries              => 10000,
    osd_pg_log_trim_min                 => 100,
    osd_enable_op_tracker               => 'true',
    osd_num_op_tracker_shard            => 32,

    # osd heartbeat
    osd_heartbeat_interval              => 6,
    osd_heartbeat_grace                 => 20,
    osd_heartbeat_min_peers             => 10,
    osd_mon_heartbeat_interval          => 30,
    osd_mon_report_interval_max         => 120,
    osd_mon_report_interval_min         => 5,
    osd_pg_stat_report_interval_max     => 500,
    osd_mon_ack_timeout                 => 30,

    # osd agent
    osd_agent_max_ops                   => 4,
    osd_agent_min_evict_effort          => 0.1,
    osd_agent_quantize_effort           => 0.1,
    osd_agent_delay_time                => 5.0,
    osd_agent_hist_halflife             => 1000,
    osd_agent_slop                      => 0.02,

    # cache tier
    osd_pool_default_hit_set_bloom_fpp          => 0.05,
    osd_pool_default_cache_target_dirty_ratio   => 0.4,
    osd_pool_default_cache_target_full_ratio    => 0.8,
    osd_pool_default_cache_min_flush_age        => 0,
    osd_pool_default_cache_min_evict_age        => 0,
    osd_hit_set_min_size                        => 1000,
    osd_hit_set_max_size                        => 100000,
    osd_hit_set_namespace                       => ".ceph-internal",
    osd_tier_default_cache_mode                 => "writeback",
    osd_tier_default_cache_hit_set_count        => 4,
    osd_tier_default_cache_hit_set_period       => 1200,
    osd_tier_default_cache_hit_set_type         => "bloom",
    osd_tier_default_cache_min_read_recency_for_promote  => 1,


    # osd leveldb
    leveldb_write_buffer_size    => 8388608,
    leveldb_cache_size           => 134217728,
    leveldb_block_size           => 0,
    leveldb_bloom_size           => 0,
    leveldb_max_open_files       => 0,
    leveldb_compression          => 'true',
    leveldb_paranoid             => 'false',
    leveldb_compact_on_mount     => 'false',

    # osd journal
    journal_max_corrupt_search      => 10485760,
    journal_block_align             => 'true',
    journal_write_header_frequency  => 0,
    journal_max_write_bytes         => 10485760,
    journal_max_write_entries       => 200,
    journal_queue_max_ops           => 30000,
    journal_queue_max_bytes         => 3355443200,
    journal_align_min_size          => 65536,
    journal_replay_from             => 0,
    journal_zero_on_create          => 'false',
    journal_ignore_corruption       => 'false',
    journal_discard                 => 'false',

    # osd filestore
    filestore_omap_header_cache_size     => 1024,
    filestore_max_inline_xattr_size_xfs  => 65536,
    filestore_max_inline_xattrs_xfs      => 10,
    filestore_max_alloc_hint_size        => 1048576,
    filestore_max_sync_interval          => 5,
    filestore_min_sync_interval          => 0.01,
    filestore_fiemap                     => 'false',
    filestore_fadvise                    => 'true',
    filestore_xfs_extsize                => 'true',
    filestore_queue_max_ops              => 500,
    filestore_queue_max_bytes            => 104857600,
    filestore_queue_committing_max_ops   => 500,
    filestore_queue_committing_max_bytes => 104857600,
    filestore_op_threads                 => 2,
    filestore_op_thread_timeout          => 60,
    filestore_op_thread_suicide_timeout  => 180,
    filestore_commit_timeout             => 600,
    filestore_fiemap_threshold           => 4096,
    filestore_merge_threshold            => 10,
    filestore_split_multiple             => 2,
    filestore_fd_cache_size              => 1024,
    filestore_fd_cache_shards            => 16,
    filestore_wbthrottle_enable                    => 'true',
    filestore_wbthrottle_xfs_ios_hard_limit        => 5000,
    filestore_wbthrottle_xfs_bytes_hard_limit      => 419430400,
    filestore_wbthrottle_xfs_inodes_hard_limit     => 5000,      #must be less the fd limit
    filestore_wbthrottle_xfs_ios_start_flusher     => 500,
    filestore_wbthrottle_xfs_bytes_start_flusher   => 41943040,
    filestore_wbthrottle_xfs_inodes_start_flusher  => 500,

    # osd backfill and recovery
    osd_max_backfills                 => 2,
    osd_backfill_full_ratio           => 0.85,
    osd_backfill_retry_interval       => 10.0,
    osd_backfill_scan_min             => 16,
    osd_backfill_scan_max             => 64,
    osd_recovery_threads              => 1,
    osd_recovery_thread_timeout       => 30,
    osd_recovery_delay_start          => 0,
    osd_recovery_max_active           => 4,
    osd_recovery_max_single_start     => 1,
    osd_recovery_max_chunk            => 8388608,
    osd_recovery_forget_lost_objects  => 'false',
    osd_recovery_op_priority          => 10,
    osd_min_recovery_priority         => 0,
    osd_recovery_op_warn_multiple     => 16,

    # osd scrub
    osd_scrub_thread_timeout          => 60,
    osd_scrub_thread_suicide_timeout  => 60,
    osd_scrub_finalize_thread_timeout => 600,
    osd_scrub_invalid_stats           => 'true',
    osd_max_scrubs                    => 1,
    osd_scrub_begin_hour              => 1,
    osd_scrub_end_hour                => 5,
    osd_scrub_load_threshold          => 0.5,
    osd_scrub_min_interval            => 86400,
    osd_scrub_max_interval            => 604800,
    osd_scrub_chunk_min               => 2,
    osd_scrub_chunk_max               => 10,
    osd_scrub_sleep                   => 0,
    osd_deep_scrub_interval           => 604800,
    osd_deep_scrub_stride             => 524288,
    osd_deep_scrub_update_digest_min_age  => 7200,
  }
}
