class kalimdor::options::base_osd {

  $osd_options = {
    # osd client
    osd_client_message_cap            => undef,
    osd_client_message_size_cap       => undef,
    osd_client_op_priority            => undef,
    ms_dispatch_throttle_bytes        => undef,

    # osd op
    osd_pg_object_context_cache_count   => 640,
    osd_op_threads                      => 8,
    osd_op_pq_max_tokens_per_priority   => undef,
    osd_op_pq_min_cost                  => undef,
    osd_op_num_threads_per_shard        => undef,      # related to the number of cpu cores
    osd_op_num_shards                   => undef,      # related to pg numbers
    osd_op_thread_timeout               => undef,
    osd_op_thread_suicide_timeout       => undef,
    osd_op_complaint_time               => undef,      # related to heartbeat interval
    osd_op_log_threshold                => undef,
    osd_op_history_size                 => undef,
    osd_op_history_duration             => undef,
    osd_min_pg_log_entries              => undef,
    osd_max_pg_log_entries              => undef,
    osd_pg_log_trim_min                 => undef,
    osd_enable_op_tracker               => 'true',
    osd_num_op_tracker_shard            => undef,

    # osd heartbeat
    osd_heartbeat_interval              => 3,
    osd_heartbeat_grace                 => 5,
    osd_heartbeat_min_peers             => undef,
    osd_mon_heartbeat_interval          => undef,
    osd_mon_report_interval_max         => undef,
    osd_mon_report_interval_min         => 2,
    osd_pg_stat_report_interval_max     => undef,
    osd_mon_ack_timeout                 => undef,

    # osd agent
    osd_agent_max_ops                   => undef,
    osd_agent_min_evict_effort          => undef,
    osd_agent_quantize_effort           => undef,
    osd_agent_delay_time                => undef,
    osd_agent_hist_halflife             => undef,
    osd_agent_slop                      => undef,

    # cache tier
    osd_pool_default_hit_set_bloom_fpp          => undef,
    osd_pool_default_cache_target_dirty_ratio   => undef,
    osd_pool_default_cache_target_full_ratio    => undef,
    osd_pool_default_cache_min_flush_age        => undef,
    osd_pool_default_cache_min_evict_age        => undef,
    osd_hit_set_min_size                        => undef,
    osd_hit_set_max_size                        => undef,
    osd_hit_set_namespace                       => undef,
    osd_tier_default_cache_mode                 => undef,
    osd_tier_default_cache_hit_set_count        => undef,
    osd_tier_default_cache_hit_set_period       => undef,
    osd_tier_default_cache_hit_set_type         => undef,
    osd_tier_default_cache_min_read_recency_for_promote  => undef,


    # osd leveldb
    leveldb_write_buffer_size    => undef,
    leveldb_cache_size           => undef,
    leveldb_block_size           => undef,
    leveldb_bloom_size           => undef,
    leveldb_max_open_files       => undef,
    leveldb_compression          => undef,
    leveldb_paranoid             => undef,
    leveldb_compact_on_mount     => undef,

    # osd journal
    journal_max_corrupt_search      => undef,
    journal_block_align             => undef,
    journal_write_header_frequency  => undef,
    journal_max_write_bytes         => undef,
    journal_max_write_entries       => undef,
    journal_align_min_size          => undef,
    journal_replay_from             => undef,
    journal_zero_on_create          => undef,
    journal_ignore_corruption       => undef,
    journal_discard                 => 'true',
    journal_throttle_low_threshhold  => undef,
    journal_throttle_high_threshhold => undef,
    journal_throttle_high_multiple   => 1,
    journal_throttle_max_multiple    => 2,
    

    # osd filestore
    filestore_omap_header_cache_size     => 10240,
    filestore_max_inline_xattr_size_xfs  => undef,
    filestore_max_inline_xattrs_xfs      => undef,
    filestore_max_alloc_hint_size        => 1048576,
    filestore_max_sync_interval          => undef,
    filestore_min_sync_interval          => undef,
    filestore_fiemap                     => 'true',
    filestore_fadvise                    => 'true',
    filestore_xfs_extsize                => 'true',
    filestore_punch_hole                 => 'true',
    filestore_seek_data_hole             => 'false',
    filestore_queue_max_ops              => undef,
    filestore_queue_max_bytes            => undef,
    filestore_caller_concurrency         => undef,
    filestore_expected_throughput_bytes  => undef,
    filestore_expected_throughput_ops    => undef,
    filestore_queue_max_delay_multiple   => 2,
    filestore_queue_high_delay_multiple  => 1,
    filestore_queue_low_threshhold       => undef,
    filestore_queue_high_threshhold      => undef,
    filestore_op_threads                 => undef,
    filestore_op_thread_timeout          => undef,
    filestore_op_thread_suicide_timeout  => undef,
    filestore_commit_timeout             => undef,
    filestore_fiemap_threshold           => undef,
    filestore_merge_threshold            => undef,
    filestore_split_multiple             => undef,
    filestore_fd_cache_size              => undef,
    filestore_fd_cache_shards            => undef,
    filestore_wbthrottle_enable                    => undef,
    filestore_wbthrottle_xfs_ios_hard_limit        => undef,
    filestore_wbthrottle_xfs_bytes_hard_limit      => undef,
    filestore_wbthrottle_xfs_inodes_hard_limit     => undef,      #must be less the fd limit
    filestore_wbthrottle_xfs_ios_start_flusher     => undef,
    filestore_wbthrottle_xfs_bytes_start_flusher   => undef,
    filestore_wbthrottle_xfs_inodes_start_flusher  => undef,

    # osd backfill and recovery
    osd_max_backfills                 => 1,
    osd_backfill_full_ratio           => undef,
    osd_backfill_retry_interval       => undef,
    osd_backfill_scan_min             => 4,
    osd_backfill_scan_max             => 16,
    osd_recovery_threads              => undef,
    osd_recovery_thread_timeout       => undef,
    osd_recovery_delay_start          => undef,
    osd_recovery_max_active           => 1,
    osd_recovery_max_single_start     => 1,
    osd_recovery_max_chunk            => undef,
    osd_recovery_forget_lost_objects  => undef,
    osd_recovery_op_priority          => 1,
    osd_min_recovery_priority         => 0,
    osd_recovery_op_warn_multiple     => undef,

    # osd scrub
    osd_scrub_thread_timeout          => undef,
    osd_scrub_thread_suicide_timeout  => undef,
    osd_scrub_finalize_thread_timeout => undef,
    osd_scrub_invalid_stats           => undef,
    osd_max_scrubs                    => 1,
    osd_scrub_begin_hour              => 1,
    osd_scrub_end_hour                => 5,
    osd_scrub_load_threshold          => undef,
    osd_scrub_min_interval            => undef,
    osd_scrub_max_interval            => undef,
    osd_scrub_chunk_min               => 2,
    osd_scrub_chunk_max               => 10,
    osd_scrub_sleep                   => undef,
    osd_deep_scrub_interval           => undef,
    osd_deep_scrub_stride             => undef,
    osd_deep_scrub_update_digest_min_age  => undef,
  }
}
